params = dict(
    device='cuda',
    epochs=1e6,
    # epochs=10,
    lr=8.5e-5,
    gamma=0.1,
    mp_steps=10,
    embedding_dim=128,
    dim=2,
    proc_hidden_dim=128,
    encoder_hidden_dim=128,
    decoder_hidden_dim=128,
    noise_std=6.7e-4,
    vel_context=6,
    batch_size=2,
    model_save_interval=5e4,
    decay_interval=5e6,
)
